import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Minus, Plus } from "lucide-react";
import { emptyConfiguration, quoteMenuItem, type MenuItem } from "../../api/menu";
import { Modal } from "../../components/Modal";
export function GuestItemDialog({ item, publicId, onClose }: { item: MenuItem; publicId?: string; onClose: () => void }) {
  const config = item.configuration ?? emptyConfiguration();
  const [variantId, setVariantId] = useState(config.variants.find((v) => v.id === config.default_variant_id && v.is_available)?.id ?? config.variants.find((v) => v.is_available)?.id ?? null);
  const [quantities, setQuantities] = useState<Record<string, number>>(() => Object.fromEntries(config.modifier_groups.flatMap((g) => g.options.filter((o) => o.is_available).map((o) => [o.id, o.default_quantity]))));
  const modifiers = useMemo(() => Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([option_id, quantity]) => ({ option_id, quantity })), [quantities]);
  const incomplete = config.modifier_groups.some((g) => { const count = g.options.reduce((sum, o) => sum + (quantities[o.id] ?? 0), 0); return count < g.min_quantity || count > g.max_quantity; });
  const quote = useQuery({ queryKey: ["menu-quote", publicId, item.id, variantId, modifiers], queryFn: ({ signal }) => quoteMenuItem(publicId!, item.id, variantId, modifiers, signal), enabled: Boolean(publicId) && !incomplete, retry: false });
  const previewPrice = (config.variants.find((v) => v.id === variantId)?.price_minor ?? item.price_minor) + config.modifier_groups.reduce((total, g) => total + g.options.reduce((sum, o) => sum + (quantities[o.id] ?? 0) * (variantId && o.price_by_variant[variantId] !== undefined ? o.price_by_variant[variantId] : o.price_minor), 0), 0);
  const amount = publicId ? quote.data?.unit_price_minor : incomplete ? undefined : previewPrice;
  return <Modal title={item.name} onClose={onClose} className="guest-item-dialog"><div className="dialog-body guest-configuration">
    {item.image_url && <img className="guest-item-photo" src={item.image_url} alt={item.name} />}{item.description && <p className="muted">{item.description}</p>}
    {!!config.variants.length && <fieldset className="guest-options"><legend>Размер</legend>{config.variants.map((variant) => <label className="guest-choice" key={variant.id}><input type="radio" name="guest-size" value={variant.id} checked={variantId === variant.id} disabled={!variant.is_available} onChange={() => setVariantId(variant.id)} /><span>{variant.name}{!variant.is_available && <small>Нет в наличии</small>}</span><strong>{(variant.price_minor / 100).toLocaleString("ru-RU")} ₽</strong></label>)}</fieldset>}
    {config.modifier_groups.map((group) => <fieldset className="guest-options" key={group.id}><legend>{group.name}<small>{group.min_quantity ? `Обязательно · ${group.min_quantity === group.max_quantity ? group.min_quantity : `${group.min_quantity}–${group.max_quantity}`}` : `До ${group.max_quantity}`}</small></legend>{group.options.map((option) => {
      const value = quantities[option.id] ?? 0; const count = group.options.reduce((sum, o) => sum + (quantities[o.id] ?? 0), 0); const price = variantId && option.price_by_variant[variantId] !== undefined ? option.price_by_variant[variantId] : option.price_minor;
      return <div className="guest-choice" key={option.id}><span>{option.name}{!option.is_available && <small>Нет в наличии</small>}</span><strong>{price ? `+${(price / 100).toLocaleString("ru-RU")} ₽` : "Без доплаты"}</strong>{group.max_quantity === 1 ? <input type="checkbox" aria-label={option.name} checked={value > 0} disabled={!option.is_available || option.max_quantity === 0 || (value > 0 && (option.min_quantity > 0 || group.min_quantity > 0))} onChange={(event) => { const next = { ...quantities }; for (const choice of group.options) next[choice.id] = choice.id === option.id && event.target.checked ? 1 : 0; setQuantities(next); }} /> : <div className="quantity-stepper"><button className="icon-button" aria-label={`Уменьшить ${option.name}`} disabled={value <= option.min_quantity} onClick={() => setQuantities({ ...quantities, [option.id]: value - 1 })}><Minus size={14} /></button><span>{value}</span><button className="icon-button" aria-label={`Добавить ${option.name}`} disabled={!option.is_available || value >= option.max_quantity || count >= group.max_quantity} onClick={() => setQuantities({ ...quantities, [option.id]: value + 1 })}><Plus size={14} /></button></div>}</div>;
    })}</fieldset>)}
    {publicId && quote.isError && <p className="form-error" role="alert">{quote.error.message}</p>}
  </div><footer className="dialog-footer"><div><small className="muted">{publicId ? "Стоимость позиции" : "Предпросмотр цены"}</small><strong className="quoted-price">{amount !== undefined ? `${(amount / 100).toLocaleString("ru-RU")} ₽` : publicId && quote.isPending ? "Считаем…" : "Выберите добавки"}</strong></div><button onClick={onClose}>Готово</button></footer></Modal>;
}
